environments:
  production: 
    guild_id: 900151360903868476
    roles: 
      administrator: 900156515875450941
      plus: 937794034410340422
  staging:
    guild_id: 1227680269721534635
    roles:
      administrator: 1227680269792837666
      plus: 1227680269792837665

roles:
  - roles:
      - administrator
      - plus
    permissions:
      # See https://discordpy.readthedocs.io/en/stable/api.html?highlight=permissions#discord.Permissions
      administrator: true
      manage_guild: true
