guild_id: 1227680269721534635

roles:
  - role_ids:
      - 1227680269792837666
      - 1227680269792837665
    permissions:
      # See https://discordpy.readthedocs.io/en/stable/api.html?highlight=permissions#discord.Permissions
      administrator: true
      manage_guild: true